[package]
name = "wbl"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.128"
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.2"